casuper25/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from casuper25 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('', include('webpages.urls')),
    path('', include('users.urls')),
    path('', include('rewards.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from os import name
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('register/<str:camp>', my_register, name='register'),
    path('registered-camps/', camp_registration, name='camp-registration'),
    path('logout/', my_logout, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='authorization/login.html'), name='login'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='authorization/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='authorization'
                                                                                        '/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='authorization/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authorization/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', my_profile, name='profile'),
    path('campers/<str:camp>', members, name='members'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from PIL import Image


# creating custom UserProfile Account Manager
class MyAccountManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Users must have email Id")

        user = self.model(email=self.normalize_email(email), username=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email=self.normalize_email(email),
                                password=password)
        user.role = 'ADM'
        user.username = self.normalize_email(email)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


# Camps
class Camp(models.Model):
  '''
  The Camp entries.
  '''

  SOTP = 1
  GMCS = 2
  SLSIP = 3
  KSHITIJ = 4
  UGETIN = 5
  SORT = 6
  SPPT = 7
  IPRS = 8
  
  CAMP_CHOICES = (
      (SOTP, 'SOTP'),
      (GMCS, 'GMCS'),
      (SLSIP, 'SLSIP'),
      (KSHITIJ, 'KSHITIJ'),
      (UGETIN, 'UGETIN'),
      (SORT, 'SORT'),
      (SPPT, 'SPPT'),
      (IPRS, 'IPRS'),
  )

  id = models.PositiveSmallIntegerField(choices=CAMP_CHOICES, primary_key=True)

  def __str__(self):
      return self.get_id_display()


# creating custom user
class User(AbstractUser):
    email = models.EmailField(verbose_name="Email", unique=True)
    ROLE_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]
    username = models.CharField(max_length=100, unique=False, null=True, blank=True)
    batch = models.IntegerField(null=True)
    gender = models.CharField(max_length=10, choices=ROLE_CHOICES, default='Male', null=True)
    name = models.CharField(max_length=30, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    date_of_birth = models.DateField(null=True)
    college_name = models.CharField(max_length=100, null=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = MyAccountManager()

    def __str__(self):
        if self.name:
            return f'{self.name}-{self.email}'
        else:
            return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        self.username = self.email           

        img = Image.open(self.image.path)

        img_width, img_height = img.size

        output_size = (500, 500)
        box = ((img_width - min(img.size)) // 2, (img_height - min(img.size)) // 2, (img_width + min(img.size)) // 2, (img_height + min(img.size)) // 2)
        img = img.crop(box)
        img.thumbnail(output_size)
        img.save(self.image.path)


class Team(models.Model):
    camp = models.ForeignKey(Camp, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    team_points = models.IntegerField(default=0)
    url = models.URLField()
    image = models.ImageField(default='default.jpg', upload_to='team_logo')

    def __str__(self):
        return self.name


ROLE_CHOICES2 = [
    ('Committee', 'Committee'),
    ('Camper', 'Camper'),
]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    camps = models.ManyToManyField(Camp, blank=True, default=1)
    role = models.CharField(max_length=30, choices=ROLE_CHOICES2, default='Camper', null=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    points = models.IntegerField(default=0)

    def __str__(self):
        if self.user.name:
            return f'{self.user.name} Profile'
        else:
            return f'{self.user.email} Profile'

templates/authorization/login.html
{% extends 'base_page.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
        <img src="{% static 'assets/img/hero-bg.jpg' %}" class="img-fluid"  loading="lazy" >
    </div><!-- End Breadcrumbs -->

        <!-- ======= Trainers Section ======= -->
    <section id="trainers" class="trainers">
      <div class="container" data-aos="fade-up">

        <div class="section-message">
          <h2>Login</h2>
        </div>


  <div class="col-lg-8 offset-lg-2 col-12">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger btn-block" type="submit">Login</button>
            </div>
        </form>

      <p class="section-message">Forgot your password? <a href="{% url 'password_reset' %}">I can help</a></p>

  </div>

      </div>
    </section><!-- End Trainers Section -->

  </main><!-- End #main -->
{% endblock content %}

templates/authorization/password_reset.html
{% extends 'base_page.html' %}
{% load static %}
{% load crispy_forms_filters%}
{% load crispy_forms_tags %} 

{% block content %}


  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs text-breadcrumbs">
      <div class="container">
        <h2>Password Reset</h2>
        <p>We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
      </div>
    </div><!-- End Breadcrumbs -->

        <!-- ======= Trainers Section ======= -->
    <section id="trainers" class="trainers">
      <div class="container" data-aos="fade-up">

    <div class="col-lg-8 offset-lg-2 col-12">
        <form action="" method="POST">
        {% csrf_token %}

        {{form | crispy}}

        <div class="form-group">
            <button type="submit" class="btn btn-block btn-danger">Submit</button>
        </div>
        </form>
    </div>

      </div>
    </section><!-- End Trainers Section -->

  </main><!-- End #main -->
{% endblock content %}

templates/authorization/password_reset_complete.html
{% extends 'base_page.html' %}
{% load static %}

{% block content %}


  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs text-breadcrumbs">
      <div class="container">
        <h2>Password successfully changed.</h2>
      </div>
    </div><!-- End Breadcrumbs -->

    <section id="about" class="about">
      <div class="container-fluid">

        <div class="row justify-content-center">
          <div class="col-lg-8 lg-offset-2 col-12 video-box d-flex justify-content-center align-items-stretch">
            <a href="https://www.youtube.com/watch?v=3pDMLt4m7TU" class="venobox play-btn mb-4 stretched-link" data-vbtype="video" data-autoplay="true"></a>
          </div>

        </div>

      </div>
    </section><!-- End About Section -->

  </main><!-- End #main -->
{% endblock content %}

templates/authorization/password_reset_confirm.html
{% extends 'base_page.html' %}
{% load static %}
{% load crispy_forms_filters%}
{% load crispy_forms_tags %} 

{% block content %}


  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs text-breadcrumbs">
      <div class="container">
        <h2>Let's Reset the Password</h2>
      </div>
    </div><!-- End Breadcrumbs -->

        <!-- ======= Trainers Section ======= -->
    <section id="trainers" class="trainers">
      <div class="container" data-aos="fade-up">

    <div class="col-lg-8 offset-lg-2 col-12">
        <form action="" method="POST">
        {% csrf_token %}

        {{form | crispy}}

        <div class="form-group">
            <button type="submit" class="btn btn-block btn-danger">Submit</button>
        </div>
        </form>
    </div>

      </div>
    </section><!-- End Trainers Section -->

  </main><!-- End #main -->
{% endblock content %}

templates/authorization/password_reset_done.html
{% extends 'base_page.html' %}
{% load static %}

{% block content %}


  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs text-breadcrumbs">
      <div class="container">
        <h2>Please Check your mail</h2>
      </div>
    </div><!-- End Breadcrumbs -->

    <section id="about" class="about">
      <div class="container-fluid">

        <div class="row justify-content-center">
          <div class="col-lg-8 lg-offset-2 col-12 video-box d-flex justify-content-center align-items-stretch">
            <a href="https://www.youtube.com/watch?v=3pDMLt4m7TU" class="venobox play-btn mb-4 stretched-link" data-vbtype="video" data-autoplay="true"></a>
          </div>

        </div>

      </div>
    </section><!-- End About Section -->

  </main><!-- End #main -->
{% endblock content %}

templates/authorization/register.html
{% extends 'base_page.html' %}
{% load static %}
{% load crispy_forms_filters%}
{% load crispy_forms_tags %} 

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/css/bootstrap-multiselect.css" integrity="sha512-DJ1SGx61zfspL2OycyUiXuLtxNqA3GxsXNinUX3AnvnwxbZ+YQxBARtX8G/zHvWRG9aFZz+C7HxcWMB0+heo3w==" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/js/bootstrap-multiselect.js" integrity="sha512-5EvDL79fM8WJcOk77QpsZ8DawGlSfbOZ/ycRPz0bxRgtiOFEMj8taAoqmm7AR4p2N+A6VBLg/Ar30L8qbPw1pQ==" crossorigin="anonymous"></script>

{% endblock custom_css %}

{% block content %}


  <main id="main" data-aos="fade-in">


    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
        <img src="{{banner.url}}" class="img-fluid"  loading="lazy" >
    </div><!-- End Breadcrumbs -->

        <!-- ======= Trainers Section ======= -->
    <section id="trainers" class="trainers">
      <div class="container" data-aos="fade-up">

        <div class="section-message">
          <h2>{{camp.heading}}</h2>
          <p>{{camp.sub_heading}}</p>
        </div>

{% if camp.is_open %}
    <div class="col-lg-8 offset-lg-2 col-12">
        <script type="text/javascript">
            $(document).ready(function() {
                $('#boot-multiselect-demo').multiselect({
                includeSelectAllOption: true,
                buttonWidth: 250,
                enableFiltering: true
            });
            });
        </script>
        <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{form | crispy}}

        <div class="form-group">
            <button type="submit" class="btn btn-block btn-danger">Submit</button>
        </div>
        </form>
    </div>

{% else %}

{% if camp.error_image %}
  <img src="{{camp.error_image.url}}" class="img-fluid"  loading="lazy" >
{% else %}
  <img src="{% static 'assets/img/coming.jpg' %}" class="img-fluid"  loading="lazy" >
{% endif %}


{% endif %}


      </div>
    </section><!-- End Trainers Section -->

  </main><!-- End #main -->
{% endblock content %}

{% block custom_js %}
<script>
        $(function () {
            $("#id_date_of_birth").datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0",
            }).attr("autocomplete", "off");
});
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.js" integrity="sha512-s5u/JBtkPg+Ff2WEr49/cJsod95UgLHbC00N/GglqdQuLnYhALncz8ZHiW/LxDRGduijLKzeYb7Aal9h3codZA==" crossorigin="anonymous"></script>

{% endblock custom_js %}